### ISSUE TITLE
'level', 'label', and 'lavel' in Section 4.1.2 and Figure 190

### ISSUE THREAD

**Issue by tgraham-antenna** [w3c/jlreq#106]
https://w3c.github.io/jlreq/#elements-of-block-heading

Section 4.1.2, Elements of Block Heading (別行見出しの構成), includes:

> JIS X 4051 describes the elements of a block heading as follows: top level heading, medium level heading and low level heading have to have a label name, number, heading title and heading sub-title (see Figure 190). Note that the label name, number and heading sub-title are not mandatory.

- It is not helpful that the first sentence describes four things as required and then the second sentence says that, by the way, three of the required things aren't required
- It might be better to add change 'low level heading have' to 'low level heading each have'
- 'top level heading' could be 'top-level heading', and so on
- 'sub-title' should be 'subtitle' (four times in text and twice in Figure 190 but already 'subtitle' in the glossary)
- The first use of 'sub-title' does not link to the glossary
- 'label name' is a tautology, since a label is a name.  It might be better to change 'label' to 'level' for the English even though JIS X 4051 uses 'ラベル名'.
- The first use of 'label name' does not link to the glossary entry
- Figure 190 uses 'lavel'
- Figure 190 labels the space between the heading number/level and the heading text as 'space between label name and number'.  It isn't (even though the Japanese figure is the same as Figure 25 in JIS X 4051).

**Comment by himorin** [comment]
>     * It is not helpful that the first sentence describes four things as required and then the second sentence says that, by the way, three of the required things aren't required
>     * It might be better to add change 'low level heading have' to 'low level heading each have'

Comparing JIS X 4051 and Japanese/English text, it seems both has some mis-writting, that JIS states three heading exists and their requirements.
For three English definitions, there is inconsistency between text and glossary, will try to do something (in an another issue).

>     * 'top level heading' could be 'top-level heading', and so on

Document wide, we use 'top level' etc. without '-' including glossary. 

>     * 'sub-title' should be 'subtitle' (four times in text and twice in Figure 190 but already 'subtitle' in the glossary)
>     * The first use of 'sub-title' does not link to the glossary

Fix them

>     * 'label name' is a tautology, since a label is a name.  It might be better to change 'label' to 'level' for the English even though JIS X 4051 uses 'ラベル名'.
>     * The first use of 'label name' does not link to the glossary entry

We'd keep this as is for now. This could be something like label pre-/post-fix, but this document imports various names and definitions from Japanese, which are not in English.
Fix for glossary link.

>     * Figure 190 uses 'lavel'

Let me file a separate issue on figure(s).

>     * Figure 190 labels the space between the heading number/level and the heading text as 'space between label name and number'.  It isn't (even though the Japanese figure is the same as Figure 25 in JIS X 4051).

Shall be fixed in image. It's a space between heading text and number+label name. (also in Japanese)
