### ISSUE TITLE
Update URL when the language is switched

### ISSUE THREAD

**Issue by kojiishi** [w3c/jlreq#236]
Often I find contents, then switch language, copy URL, and paste to somewhere, without noticing that the  URL may show different language than I'm seeing.

Great if language switching can update the `?lang=xx` part of the URL.

**Comment by xfq** [comment]
I thought about creating a PR about this before the publication of the current /TR version, but finally did not submit the PR, since I can see both advantages and disadvantages of it.

The advantage is that sharing it with others can reproduce the current state (language) of the document. The disadvantage is that the user (at least for me) may want a "cleaner" URL and doesn't want to get these statuses. Although the parameter can be removed manually (just like the [UTM parameters](https://en.wikipedia.org/wiki/UTM_parameters), although the purpose is different), it is a bit troublesome.

That said, it's not a strong opinion and I won't object if this feature is added.

**Comment by kojiishi** [comment]
@xfq Thanks, I agree it has both pros and cons. I think the advantage is bigger, but it is understandable if others think differently.

I can create a PR, and I'll let reviewers to decide which experience they would like to take.
